yet another trial for nuget push

diff --git a/.github/workflows/nuget.yaml b/.github/workflows/nuget.yaml
--- a/.github/workflows/nuget.yaml
+++ b/.github/workflows/nuget.yaml
@@ -23,18 +23,24 @@ jobs:
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: 6.0.x
-    - name: Build
-      working-directory: ./src
-      run: dotnet build /p:Version=${{ github.event.release.tag_name }}
-    - name: Test
-      working-directory: ./src
-      run: dotnet test /p:Version=${{ github.event.release.tag_name }} --no-build
-    - name: Pack
-      working-directory: ./src
-      run: dotnet pack /p:Version=${{ github.event.release.tag_name }} --no-build --output .
-    - uses: actions/upload-artifact@v3
-      if: success() || failure()
-      with:
-        name: nuget-artifact
-        path: '**/*.nupkg'
-        retention-days: 1
+    - name: Set VERSION variable from tag
+      run: |
+        version=$(echo ${{ github.event.release.tag_name }} | cut -d- -f1)
+        echo "VERSION=${version}" >> $GITHUB_ENV
+    - name: Dump env
+      run: env | sort
+    # - name: Build
+    #   working-directory: ./src
+    #   run: dotnet build /p:Version=${VERSION}
+    # - name: Test
+    #   working-directory: ./src
+    #   run: dotnet test /p:Version=${VERSION} --no-build
+    # - name: Pack
+    #   working-directory: ./src
+    #   run: dotnet pack /p:Version=${VERSION} --no-build --output .
+    # - uses: actions/upload-artifact@v3
+    #   if: success() || failure()
+    #   with:
+    #     name: nuget-artifact
+    #     path: '**/*.nupkg'
+    #     retention-days: 1
